--- 
version: "3"
services: 
  nginx:
    env_file: nginx.env
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    image: "renuraj18/nginx"
    networks: 
      - my-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_config:/etc/nginx
      - nginx_resources:/resources
      
volumes:
  nginx_config:
  nginx_resources:
#    driver: rexray/ebs
    

networks:
  my-network:
    driver: overlay
    external: true
