---

version: "3"

services:
  tomcat:
    env_file: tomcat_filebeat.env
    deploy:
      placement:
        constraints:
          - node.hostname == ip-172-31-2-150
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
    image: projectethan007/tomcat:1.0.0
    networks:
      -  my-network
    ports:
      - "8888:8080"
networks:
  my-network:
   driver: overlay
   external: true
