---

version: "3"

services:
  dashing:
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: any
    image: renuraj18/dashing:1.0
    networks:
      - my-network
    expose:
      - 3030
    volumes:
      - "dashing_board:/dashing"

volumes:
  dashing_board:

networks:
  my-network:
    driver: overlay
    external: true 
