---
version: "3"
services:
  jenkins:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    image: "jenkins"
    networks:
      - my-network
    ports:
      - "8080:8080"
    volumes:
      - "jenkins-home:/var/jenkins_home"

volumes:
  jenkins-home:
#    driver: rexray/ebs

networks:
  my-network:
    driver: overlay
    external: true
